destination: ./_site
auto: false
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
exclude: readme.md
title: LameStation

pages_list:
    Home: '/'
    About: '/about/'
    Learn: '/learn/'
    Blog: '/blog/'
    Games: '/games/'
    Shop: '/shop/'
    Contact: '/contact/'

games_list:
    AKnightOut: 'aknightout'
    Brettris: 'brettris'
    FrappyBard: 'frappybard'
    Pikemanz: 'pikemanz'
    piXel: 'pixel'

