destination: ./_site
safe: true
lsi: false
port: 4000
highlighter: pygments
permalink: date
title: LameStation

pages_list:
    Home: '/'
    About: '/about/'
    Learn: '/learn/'
    Blog: '/blog/'
    Games: '/games/'
    Shop: '/shop/'
    Contact: '/contact/'

collections:
    games:
        output: true
        permalink: /games/:path/
