destination: ./_site
auto: false
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
exclude: readme.md
title: LameStation
title_bar:
  - Home
  - About
  - Images
  - News
  - Manual
manual_index:
  audio:
    - adsr
    - pwm_dac
    - waveformgenerator
    - midi
    - frequencytiming
  display:
    - blitting
    - contentgeneration
