destination: ./_site
auto: false
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
exclude: readme.md
title: LameStation
title_bar:
  bacon:
    - Other
  audio:
    - Home
    - About
    - Images
    - News
    - Manual
  display:
    - Arfff
    - Noof
    - Nicce
    - IOJsdfd
  narfff:
    - Nope
manual_index:
  audio:
    - adsr
    - pwm_dac
    - waveformgenerator
    - timegranularity
    - midi
    - frequencytiming
  display:
    - blitting
    - contentgeneration
