destination: ./_site
safe: true
lsi: false
port: 4000
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

pages_list:
    Start: 
        - '/start/'
    Help:
        - '/help/'
    Games:
        - '/games/'
    Buy:
        - '/buy/'
    News:
        - '/news/'
    About:
        - Contact: '/contact/'
        - Mailing List: '/mail/'
        - FAQ: '/faq/'

collections:
    games:
        output: true
        permalink: /games/:path/
