destination: ./_site
safe: true
lsi: false
port: 4000
highlighter: pygments
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation
markdown: kramdown

pages_list:
    Home: '/'
    Learn: '/learn/'
    Games: '/games/'
    About: '/about/'

collections:
    games:
        output: true
        permalink: /games/:path/
