destination: ./_site
safe: true
lsi: false
port: 4000
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

pages_list:
    Home:
        - '/'
    Start: 
        - '/start/'
    Learn:
        - 'https://bweir.gitbooks.io/lamestation-book/content/'
    Games:
        - '/games/'
    Shop:
        - '/shop/'
    News:
        - '/news/'
    About: 
        - Contact: '/contact/'

collections:
    games:
        output: true
        permalink: /games/:path/
