destination: ./_site
safe: true
lsi: false
port: 4000
highlighter: pygments
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation
markdown: kramdown

pages_list:
    Home: '/'
<<<<<<< HEAD
    Learn: 'https://bweir.gitbooks.io/lamestation-book/content/'
    SDK: 'https://github.com/lamestation/lamestation-sdk/releases/latest'
    Games: '/games/'
    Shop: '/shop/'
    News: '/news/'
    About: '/about/'

collections:
    games:
        output: true
        permalink: /games/:path/
