destination: ./_site
safe: true
lsi: false
port: 4000
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

name: LameStation News
description: The latest news at LameStation headquarters
url: http://www.lamestation.com

pages_list:
    Start: 
        - '/start/'
    Games:
        - '/games/'
    Buy:
        - '/buy/'
    Resources:
        - Downloads: '/download/'
        - Assembly: '/build/'
        - Programming: '/code/'
        - More: '/more/'
    Support:
        - Forum: 'https://forum.lamestation.com'
        - Contact Us: '/contact/'
    About:
        - Mailing List: '/mail/'
        - News: '/news/'
        - FAQ: '/faq/'

collections:
    games:
        output: true
        permalink: /games/:path/
