destination: ./_site
safe: true
lsi: false
port: 4000
highlighter: pygments
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

pages_list:
    Home: '/'
    About: '/about/'
    Learn: '/learn/'
    News: '/news/'
    Games: '/games/'
    Shop: '/shop/'
    Contact: '/contact/'

collections:
    games:
        output: true
        permalink: /games/:path/
