destination: ./_site
auto: false
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
exclude: readme.md
title: LameStation
title_bar:
  - Home
  - About
  - Images
  - News
manual_index:
  design:
    - proppa
    - specifications
    - input
    - prototyping
    - bom
  audio:
    - adsr
    - pwm_dac
    - waveformgenerator
    - midi
    - frequencytiming
    - things_to_look_into
  display:
    - blitting
    - contentgeneration
  tools:
    - frequencytablegenerator
    - intro
    - mathfuncgen
    - img2dat
    - allegfuncgen
  applications:
    - SDcard
    - midi_interfacing
    - tank_battle
    - wireless
