destination: ./_site
safe: true
lsi: false
port: 4000
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

pages_list:
    Home:
        - '/'
    Buy:
        - '/buy/'
    Start: 
        - '/start/'
    Learn:
        - 'https://bweir.gitbooks.io/lamestation-book/content/'
    Games:
        - '/games/'
    About:
        - Contact: '/contact/'
        - Mailing List: '/mail/'
        - News: '/news/'
        - FAQ: '/faq/'

collections:
    games:
        output: true
        permalink: /games/:path/
